import Header from '@/src/components/Header'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Vini Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main>
        <h1>
          VINI STORE
        </h1>

        <p>
          Mais Detalhes Sobre os Produtos abaixo
        </p>
      </main>
    </>
  )
}

export default Home